### ISSUE TITLE
Add empty __init__.py so we can use as submodule easily.

### ISSUE THREAD

**Issue by JakeWharton** [dbr/tvdb_api#6]
```
touch __init__.py
git commit -a -m "Added __init__.py. Closes issue 6."
git push
```

**Comment by dbr** [comment]
Closing, old ticket and not likely to add a top-level `__init__.py` file to support this, as it is an interesting idea but kind of.. unconventional.

Currently, `tvdb_api.py` for now is a single self-contained .py file in the top of the repo, so should still be fairly easy to use in a submodule manner (`sys.path.append("./tvdb_checkout"); import tvdb_api` instead of just `sys.path.append("."); ...`)
