### ISSUE TITLE
Add git tag for 2.0 release

### ISSUE THREAD

**Issue by koobs** [dbr/tvdb_api#61]
Currently the tag is missing. Please add a 2.0 git tag referencing the commit that was used to upload/release to PyPI

**Comment by dbr** [comment]
Oops, good point - thanks!

I think I forgot to push the version-string-bump commit and tag from other computer.. but the released tarball matches bc654c884ed9722af0cf19b9d8c54ca9af5e7727 ignoring the version string being changed from `2.0-dev` to 2.0` so I'll probably just tag that (since there has been subsequent commits)

**Comment by dbr** [comment]
Done, https://github.com/dbr/tvdb_api/tree/2.0

**Comment by koobs** [comment]
<3 thank you
