### ISSUE TITLE
create .nfo file for episodes

### ISSUE THREAD

**Issue by brianjmurrell** [dbr/tvdb_api#63]
Not sure if you will find this relevant to your project or not, but I thought I would suggest...

It might be interesting to have a library function that produces an episode `.nfo` file from an episode object.

Maybe this kind of mapping already exists somewhere that I am just not aware of.

**Comment by dbr** [comment]
I believe this would best live in a separate project, rather than in `tvdb_api` - this project should just exist as an interface to TheTVDB.com.

My other concern is there seems to be quite a few variations of the TV show .nfo (e.g Sonarr has 4 options: Emby, Kodi, Roksbox, WD TV) so I suspect it would require a bit of maintenance to keep the formats up-to-date

Thanks for the idea though!
